// =====================================================
// 📊 SECTOR DATA
// src/components/SectorAnalyzer/data.ts
// =====================================================
// UPDATED: 10 topHoldings per sector for HeatMapTab (Top 10 Movers)
// =====================================================

import type { Sector } from './types';

export const sectors: Sector[] = [
  {
    id: '1', name: 'Technology', ticker: 'XLK', icon: 'Cpu', price: 215.80, changePercent: 1.62,
    weekChange: 4.2, monthChange: 8.5, ytdChange: 12.3, momentum: 75, relativeStrength: 82,
    sentiment: 'bullish', beta: 1.15, marketCap: '$15.2T', spWeight: 29.5, companies: 68,
    description: 'Software, Hardware, Semiconductors',
    verdict: { rating: 78, signal: 'OVERWEIGHT', summary: 'AI infrastructure boom supports premium valuations. Selective buying on pullbacks recommended.' },
    vsMarket: [
      { period: '1W', sectorReturn: 1.2, spyReturn: 0.8, alpha: 0.4 },
      { period: '1M', sectorReturn: 4.5, spyReturn: 3.1, alpha: 1.4 },
      { period: '3M', sectorReturn: 8.2, spyReturn: 5.8, alpha: 2.4 },
      { period: 'YTD', sectorReturn: 12.3, spyReturn: 9.1, alpha: 3.2 },
    ],
    fundamentals: { peForward: 28.5, peVsSpAvg: 22, evEbitda: 18.2, evEbitdaVsSpAvg: 14, revGrowth: 12.3, revGrowthVsSpAvg: 5, earningsGrowth: 18.5, earningsGrowthVsSpAvg: 8, valuationAssessment: 'PREMIUM (justified by growth)' },
    moneyFlow: { netInflow: 2.8, signal: 'ACCUMULATION', etfFlows: [{ ticker: 'XLK', flow: 1200 }, { ticker: 'VGT', flow: 890 }, { ticker: 'QQQ', flow: 3500 }], hedgeFundActivity: { netBuying: 4.2, newPositions: 127, closedPositions: 89 } },
    earningsCalendar: [{ date: 'Feb 5', ticker: 'GOOGL', estimate: 1.92, whisper: 2.05, impact: 'High' }, { date: 'Feb 6', ticker: 'AMZN', estimate: 1.45, whisper: 1.52, impact: 'High' }],
    subSectors: [{ name: 'Semiconductors', weight: 32, ytd: 22, pe: 35, rating: 95, signal: 'BUY' }, { name: 'Software', weight: 28, ytd: 8, pe: 28, rating: 80, signal: 'HOLD' }, { name: 'Hardware', weight: 22, ytd: 5, pe: 22, rating: 60, signal: 'HOLD' }],
    intraSectorCorrelation: { average: 0.72, historicalRange: { min: 0.55, max: 0.88 }, regime: 'NORMAL' },
    correlationBreakers: [
      { ticker: 'CRWD', name: 'CrowdStrike', normalCorrelation: 0.78, currentCorrelation: 0.52, divergencePercent: -33, type: 'BREAKOUT', reasons: ['Cybersecurity spend accelerating (+25% YoY)', 'Company-specific catalyst (FedRAMP approval)'], signal: 'BULLISH_DIVERGENCE' },
      { ticker: 'INTC', name: 'Intel', normalCorrelation: 0.82, currentCorrelation: 0.41, divergencePercent: -50, type: 'LAGGING', reasons: ['Losing market share to AMD/NVDA', 'Foundry business struggles'], signal: 'BEARISH_DIVERGENCE' },
    ],
    pairsTrades: [{ longTicker: 'NVDA', shortTicker: 'INTC', normalCorrelation: 0.72, currentCorrelation: 0.35, divergence: -51, signal: 'Long NVDA / Short INTC' }],
    etfs: [{ ticker: 'XLK', name: 'Technology Select', aum: '$62B' }, { ticker: 'VGT', name: 'Vanguard IT', aum: '$58B' }, { ticker: 'QQQ', name: 'Nasdaq 100', aum: '$250B' }],
    topHoldings: [
      { ticker: 'NVDA', name: 'NVIDIA', weight: 18.5, change: 4.2, score: 92, volumeVsAvg: 1.8, peVsSector: 45, insiderActivity: 'buy' },
      { ticker: 'AAPL', name: 'Apple', weight: 15.2, change: 1.8, score: 85, volumeVsAvg: 1.1, peVsSector: -12, insiderActivity: 'none' },
      { ticker: 'MSFT', name: 'Microsoft', weight: 14.8, change: 2.1, score: 88, volumeVsAvg: 0.9, peVsSector: 8, insiderActivity: 'sell' },
      { ticker: 'AVGO', name: 'Broadcom', weight: 5.2, change: 3.5, score: 81, volumeVsAvg: 2.1, peVsSector: 22, insiderActivity: 'buy' },
      { ticker: 'AMD', name: 'AMD', weight: 3.8, change: -1.2, score: 72, volumeVsAvg: 1.5, peVsSector: 18, insiderActivity: 'none' },
      { ticker: 'CRM', name: 'Salesforce', weight: 3.2, change: 0.8, score: 68, volumeVsAvg: 0.7, peVsSector: -5, insiderActivity: 'sell' },
      { ticker: 'ADBE', name: 'Adobe', weight: 2.8, change: 1.5, score: 71, volumeVsAvg: 0.8, peVsSector: 2, insiderActivity: 'none' },
      { ticker: 'INTC', name: 'Intel', weight: 1.5, change: -2.8, score: 45, volumeVsAvg: 1.2, peVsSector: -35, insiderActivity: 'sell' },
      { ticker: 'ORCL', name: 'Oracle', weight: 3.5, change: 1.9, score: 76, volumeVsAvg: 1.0, peVsSector: 5, insiderActivity: 'none' },
      { ticker: 'CSCO', name: 'Cisco', weight: 2.1, change: 0.4, score: 62, volumeVsAvg: 0.8, peVsSector: -18, insiderActivity: 'none' },
    ],
    correlations: [{ ticker: 'QQQ', correlation: 0.95 }, { ticker: 'SMH', correlation: 0.88 }, { ticker: 'XLY', correlation: 0.72 }, { ticker: 'XLF', correlation: 0.58 }, { ticker: 'XLU', correlation: -0.25 }],
    macroSensitivity: [{ factor: 'Interest Rates', sensitivity: 'High', impact: 'Higher rates compress growth valuations' }, { factor: 'GDP Growth', sensitivity: 'High', impact: 'Tech spending tied to economic expansion' }, { factor: 'Dollar Strength', sensitivity: 'Medium', impact: '~60% revenue from international' }],
    industryTrends: [{ trend: 'AI Infrastructure Buildout', impact: 'Positive', description: 'Massive capex in AI chips and data centers' }, { trend: 'Cloud Migration', impact: 'Positive', description: 'Continued enterprise shift to cloud' }, { trend: 'Regulatory Pressure', impact: 'Negative', description: 'Antitrust scrutiny on mega-caps' }],
    risks: [{ risk: 'Valuation Risk', probability: 'High', impact: 'Medium' }, { risk: 'Rate Sensitivity', probability: 'Medium', impact: 'High' }, { risk: 'China Exposure', probability: 'Medium', impact: 'High' }],
    breakoutCandidate: { ticker: 'CRWD', name: 'CrowdStrike', score: 87, correlation: 0.52, reasons: ['Low correlation = independent mover', 'Cybersecurity spend accelerating', 'Best-in-class net retention (120%+)', 'Volume accumulation pattern'], fundamentalEdge: ['Revenue growth: +32% vs sector +12%', 'Net retention rate: 120%+ (best in class)', 'FCF positive and growing'], technicalSetup: ['Consolidating 15% below ATH', 'Volume accumulation pattern (OBV rising)', 'RSI reset from overbought (now 55)'], catalysts: [{ date: 'Mar 5', event: 'Q4 Earnings' }, { date: 'Mar 15', event: 'RSA Conference' }], ownershipTailwinds: ['Insider buying: $4.2M in last 90 days', 'Institutional accumulation: +8% QoQ'], entry: '$380-395', target: '$480 (+25%)', stop: '$350 (-10%)', riskReward: '2.5:1' },
    tradeIdeas: [{ strategy: 'Sector Beta Play', trade: 'Long XLK', thesis: 'AI momentum continues', target: '+15%' }, { strategy: 'Single Stock Alpha', trade: 'Long CRWD', thesis: 'Cybersecurity breakout', target: '+25%' }, { strategy: 'Pairs Trade', trade: 'Long AMD / Short INTC', thesis: 'Market share shift', target: '+20%' }],
  },
  {
    id: '2', name: 'Healthcare', ticker: 'XLV', icon: 'Heart', price: 142.30, changePercent: -0.84,
    weekChange: -1.5, monthChange: 2.1, ytdChange: 4.8, momentum: 25, relativeStrength: 45,
    sentiment: 'neutral', beta: 0.75, marketCap: '$7.8T', spWeight: 12.1, companies: 64,
    description: 'Pharma, Biotech, Medical Devices',
    verdict: { rating: 62, signal: 'NEUTRAL', summary: 'Defensive characteristics provide stability. GLP-1 theme offers select opportunities.' },
    etfs: [{ ticker: 'XLV', name: 'Health Care Select', aum: '$38B' }],
    topHoldings: [
      { ticker: 'LLY', name: 'Eli Lilly', weight: 12.8, change: 2.5, score: 91, volumeVsAvg: 1.6, peVsSector: 55, insiderActivity: 'none' },
      { ticker: 'UNH', name: 'UnitedHealth', weight: 10.2, change: -1.2, score: 78, volumeVsAvg: 1.1, peVsSector: -8, insiderActivity: 'sell' },
      { ticker: 'JNJ', name: 'Johnson & Johnson', weight: 8.5, change: 0.3, score: 72, volumeVsAvg: 0.9, peVsSector: -15, insiderActivity: 'none' },
      { ticker: 'ABBV', name: 'AbbVie', weight: 7.2, change: -0.8, score: 74, volumeVsAvg: 1.0, peVsSector: -5, insiderActivity: 'buy' },
      { ticker: 'MRK', name: 'Merck', weight: 5.8, change: -1.5, score: 68, volumeVsAvg: 1.3, peVsSector: -12, insiderActivity: 'none' },
      { ticker: 'TMO', name: 'Thermo Fisher', weight: 4.5, change: 1.1, score: 77, volumeVsAvg: 0.8, peVsSector: 10, insiderActivity: 'none' },
      { ticker: 'ABT', name: 'Abbott Labs', weight: 4.1, change: 0.6, score: 70, volumeVsAvg: 0.9, peVsSector: -3, insiderActivity: 'none' },
      { ticker: 'PFE', name: 'Pfizer', weight: 3.2, change: -2.1, score: 42, volumeVsAvg: 1.4, peVsSector: -28, insiderActivity: 'buy' },
      { ticker: 'AMGN', name: 'Amgen', weight: 3.8, change: 1.8, score: 75, volumeVsAvg: 1.2, peVsSector: 8, insiderActivity: 'none' },
      { ticker: 'VRTX', name: 'Vertex Pharma', weight: 3.1, change: 3.2, score: 84, volumeVsAvg: 1.7, peVsSector: 30, insiderActivity: 'buy' },
    ],
    correlations: [{ ticker: 'XLP', correlation: 0.65 }, { ticker: 'SPY', correlation: 0.72 }],
    macroSensitivity: [{ factor: 'Regulation', sensitivity: 'High', impact: 'Drug pricing policy risk' }],
    industryTrends: [{ trend: 'GLP-1 Revolution', impact: 'Positive', description: 'Obesity/diabetes drugs driving growth' }],
    risks: [{ risk: 'Drug Pricing Legislation', probability: 'Medium', impact: 'High' }],
    breakoutCandidate: { ticker: 'VRTX', name: 'Vertex Pharma', score: 84, correlation: 0.48, reasons: ['CF franchise generates massive cash', 'Pain drug pipeline undervalued'], entry: '$485-500', target: '$580 (+18%)', stop: '$450 (-8%)', riskReward: '2.3:1' },
    tradeIdeas: [{ strategy: 'GLP-1 Theme', trade: 'Long LLY', thesis: 'Obesity drug dominance', target: '+20%' }],
  },
  {
    id: '3', name: 'Financials', ticker: 'XLF', icon: 'Banknote', price: 42.15, changePercent: 2.06,
    weekChange: 3.1, monthChange: 5.2, ytdChange: 8.9, momentum: 55, relativeStrength: 61,
    sentiment: 'bullish', beta: 1.08, marketCap: '$5.2T', spWeight: 13.2, companies: 72,
    description: 'Banks, Insurance, Capital Markets',
    verdict: { rating: 71, signal: 'OVERWEIGHT', summary: 'NIM stabilization and capital markets recovery support bullish outlook.' },
    etfs: [{ ticker: 'XLF', name: 'Financial Select', aum: '$35B' }],
    topHoldings: [
      { ticker: 'JPM', name: 'JPMorgan Chase', weight: 10.5, change: 2.8, score: 88, volumeVsAvg: 1.3, peVsSector: 12, insiderActivity: 'none' },
      { ticker: 'BRK.B', name: 'Berkshire Hathaway', weight: 9.8, change: 1.5, score: 85, volumeVsAvg: 0.9, peVsSector: -5, insiderActivity: 'buy' },
      { ticker: 'V', name: 'Visa', weight: 7.5, change: 1.2, score: 82, volumeVsAvg: 0.8, peVsSector: 25, insiderActivity: 'none' },
      { ticker: 'MA', name: 'Mastercard', weight: 6.8, change: 1.4, score: 80, volumeVsAvg: 0.9, peVsSector: 28, insiderActivity: 'none' },
      { ticker: 'BAC', name: 'Bank of America', weight: 5.2, change: 3.1, score: 72, volumeVsAvg: 1.5, peVsSector: -15, insiderActivity: 'none' },
      { ticker: 'WFC', name: 'Wells Fargo', weight: 4.1, change: 2.5, score: 70, volumeVsAvg: 1.2, peVsSector: -18, insiderActivity: 'none' },
      { ticker: 'GS', name: 'Goldman Sachs', weight: 3.5, change: 3.8, score: 82, volumeVsAvg: 1.8, peVsSector: 5, insiderActivity: 'buy' },
      { ticker: 'MS', name: 'Morgan Stanley', weight: 3.2, change: 2.9, score: 76, volumeVsAvg: 1.4, peVsSector: -2, insiderActivity: 'none' },
      { ticker: 'SPGI', name: 'S&P Global', weight: 2.8, change: 0.8, score: 79, volumeVsAvg: 0.7, peVsSector: 32, insiderActivity: 'none' },
      { ticker: 'BLK', name: 'BlackRock', weight: 2.5, change: 1.1, score: 77, volumeVsAvg: 0.9, peVsSector: 15, insiderActivity: 'none' },
    ],
    correlations: [{ ticker: 'TLT', correlation: -0.55 }, { ticker: 'SPY', correlation: 0.85 }],
    macroSensitivity: [{ factor: 'Interest Rates', sensitivity: 'High', impact: 'NIM expansion with higher rates' }],
    industryTrends: [{ trend: 'Capital Markets Recovery', impact: 'Positive', description: 'IPO/M&A activity picking up' }],
    risks: [{ risk: 'Credit Deterioration', probability: 'Medium', impact: 'High' }],
    breakoutCandidate: { ticker: 'GS', name: 'Goldman Sachs', score: 82, correlation: 0.65, reasons: ['Capital markets recovery', 'Trading revenue beats'], entry: '$580-600', target: '$720 (+22%)', stop: '$540 (-8%)', riskReward: '2.8:1' },
    tradeIdeas: [{ strategy: 'Rate Play', trade: 'Long XLF', thesis: 'Higher for longer', target: '+12%' }],
  },
  {
    id: '4', name: 'Energy', ticker: 'XLE', icon: 'Fuel', price: 89.45, changePercent: -2.51,
    weekChange: -4.2, monthChange: -6.8, ytdChange: -3.2, momentum: -45, relativeStrength: 28,
    sentiment: 'bearish', beta: 1.35, marketCap: '$1.8T', spWeight: 3.8, companies: 23,
    description: 'Oil & Gas, Equipment, Services',
    verdict: { rating: 42, signal: 'UNDERWEIGHT', summary: 'Weak oil prices and ESG headwinds. Contrarian opportunity for risk-tolerant investors.' },
    etfs: [{ ticker: 'XLE', name: 'Energy Select', aum: '$32B' }],
    topHoldings: [
      { ticker: 'XOM', name: 'Exxon Mobil', weight: 22.5, change: -2.1, score: 72, volumeVsAvg: 1.2, peVsSector: -5, insiderActivity: 'none' },
      { ticker: 'CVX', name: 'Chevron', weight: 18.2, change: -1.8, score: 70, volumeVsAvg: 1.1, peVsSector: -8, insiderActivity: 'none' },
      { ticker: 'COP', name: 'ConocoPhillips', weight: 7.5, change: -2.5, score: 68, volumeVsAvg: 1.3, peVsSector: -2, insiderActivity: 'none' },
      { ticker: 'EOG', name: 'EOG Resources', weight: 5.2, change: -1.5, score: 75, volumeVsAvg: 1.0, peVsSector: 3, insiderActivity: 'buy' },
      { ticker: 'SLB', name: 'Schlumberger', weight: 4.8, change: -3.2, score: 58, volumeVsAvg: 1.6, peVsSector: -10, insiderActivity: 'none' },
      { ticker: 'MPC', name: 'Marathon Petroleum', weight: 4.2, change: -1.2, score: 65, volumeVsAvg: 0.9, peVsSector: -20, insiderActivity: 'none' },
      { ticker: 'PSX', name: 'Phillips 66', weight: 3.5, change: -0.8, score: 62, volumeVsAvg: 0.8, peVsSector: -15, insiderActivity: 'none' },
      { ticker: 'VLO', name: 'Valero Energy', weight: 3.2, change: -1.9, score: 60, volumeVsAvg: 1.1, peVsSector: -22, insiderActivity: 'sell' },
      { ticker: 'OXY', name: 'Occidental', weight: 2.8, change: -3.5, score: 52, volumeVsAvg: 1.7, peVsSector: 8, insiderActivity: 'buy' },
      { ticker: 'WMB', name: 'Williams Companies', weight: 2.5, change: 0.5, score: 71, volumeVsAvg: 0.7, peVsSector: 12, insiderActivity: 'none' },
    ],
    correlations: [{ ticker: 'USO', correlation: 0.82 }],
    macroSensitivity: [{ factor: 'Oil Price', sensitivity: 'High', impact: 'Direct earnings correlation' }],
    industryTrends: [{ trend: 'Capital Discipline', impact: 'Positive', description: 'Companies returning cash vs growth' }],
    risks: [{ risk: 'Oil Price Collapse', probability: 'Medium', impact: 'High' }],
    breakoutCandidate: { ticker: 'EOG', name: 'EOG Resources', score: 75, correlation: 0.72, reasons: ['Best-in-class drilling', 'Strong FCF at $65 oil'], entry: '$118-125', target: '$145 (+18%)', stop: '$108 (-10%)', riskReward: '1.8:1' },
    tradeIdeas: [{ strategy: 'Contrarian', trade: 'Long XLE', thesis: 'Oversold bounce', target: '+10%' }],
  },
  {
    id: '5', name: 'Consumer Disc.', ticker: 'XLY', icon: 'ShoppingBag', price: 185.60, changePercent: 1.03,
    weekChange: 2.4, monthChange: 4.1, ytdChange: 7.5, momentum: 40, relativeStrength: 55,
    sentiment: 'neutral', beta: 1.12, marketCap: '$4.5T', spWeight: 10.8, companies: 52,
    description: 'Retail, Auto, Entertainment',
    verdict: { rating: 58, signal: 'NEUTRAL', summary: 'Consumer spending resilient but facing headwinds. Amazon dominates.' },
    etfs: [{ ticker: 'XLY', name: 'Consumer Disc Select', aum: '$18B' }],
    topHoldings: [
      { ticker: 'AMZN', name: 'Amazon', weight: 22.5, change: 1.8, score: 85, volumeVsAvg: 1.2, peVsSector: 35, insiderActivity: 'none' },
      { ticker: 'TSLA', name: 'Tesla', weight: 12.2, change: 2.5, score: 65, volumeVsAvg: 1.9, peVsSector: 85, insiderActivity: 'sell' },
      { ticker: 'HD', name: 'Home Depot', weight: 8.5, change: 0.8, score: 78, volumeVsAvg: 0.8, peVsSector: 5, insiderActivity: 'none' },
      { ticker: 'MCD', name: "McDonald's", weight: 5.2, change: -0.5, score: 74, volumeVsAvg: 0.7, peVsSector: -8, insiderActivity: 'none' },
      { ticker: 'NKE', name: 'Nike', weight: 3.8, change: -1.8, score: 55, volumeVsAvg: 1.4, peVsSector: -12, insiderActivity: 'none' },
      { ticker: 'LOW', name: "Lowe's", weight: 4.5, change: 1.2, score: 72, volumeVsAvg: 0.9, peVsSector: -2, insiderActivity: 'none' },
      { ticker: 'BKNG', name: 'Booking Holdings', weight: 4.1, change: 2.1, score: 81, volumeVsAvg: 1.1, peVsSector: 18, insiderActivity: 'none' },
      { ticker: 'SBUX', name: 'Starbucks', weight: 3.2, change: -0.3, score: 60, volumeVsAvg: 0.8, peVsSector: -5, insiderActivity: 'none' },
      { ticker: 'TJX', name: 'TJX Companies', weight: 3.0, change: 1.5, score: 76, volumeVsAvg: 0.9, peVsSector: 2, insiderActivity: 'buy' },
      { ticker: 'CMG', name: 'Chipotle', weight: 2.8, change: 0.9, score: 73, volumeVsAvg: 1.0, peVsSector: 42, insiderActivity: 'none' },
    ],
    correlations: [{ ticker: 'XLK', correlation: 0.72 }],
    macroSensitivity: [{ factor: 'Consumer Confidence', sensitivity: 'High', impact: 'Discretionary spending sensitive' }],
    industryTrends: [{ trend: 'E-commerce Growth', impact: 'Positive', description: 'Online penetration continues' }],
    risks: [{ risk: 'Consumer Slowdown', probability: 'Medium', impact: 'High' }],
    breakoutCandidate: { ticker: 'BKNG', name: 'Booking Holdings', score: 81, correlation: 0.55, reasons: ['Travel demand strong', 'Margin expansion'], entry: '$4,800-5,000', target: '$5,800 (+18%)', stop: '$4,400 (-10%)', riskReward: '1.8:1' },
    tradeIdeas: [{ strategy: 'E-commerce', trade: 'Long AMZN', thesis: 'AWS + retail', target: '+20%' }],
  },
  {
    id: '6', name: 'Industrials', ticker: 'XLI', icon: 'Factory', price: 118.25, changePercent: 1.24,
    weekChange: 2.8, monthChange: 4.5, ytdChange: 6.2, momentum: 48, relativeStrength: 52,
    sentiment: 'neutral', beta: 1.05, marketCap: '$3.2T', spWeight: 8.5, companies: 78,
    description: 'Aerospace, Defense, Machinery',
    verdict: { rating: 65, signal: 'NEUTRAL', summary: 'Infrastructure spending tailwind. Aerospace remains strong.' },
    etfs: [{ ticker: 'XLI', name: 'Industrial Select', aum: '$18B' }],
    topHoldings: [
      { ticker: 'CAT', name: 'Caterpillar', weight: 5.5, change: 2.2, score: 78, volumeVsAvg: 1.2, peVsSector: 8, insiderActivity: 'none' },
      { ticker: 'GE', name: 'GE Aerospace', weight: 5.2, change: 3.1, score: 84, volumeVsAvg: 1.5, peVsSector: 22, insiderActivity: 'buy' },
      { ticker: 'HON', name: 'Honeywell', weight: 4.8, change: 0.5, score: 72, volumeVsAvg: 0.8, peVsSector: -3, insiderActivity: 'none' },
      { ticker: 'UNP', name: 'Union Pacific', weight: 4.5, change: 0.8, score: 75, volumeVsAvg: 0.9, peVsSector: 5, insiderActivity: 'none' },
      { ticker: 'RTX', name: 'RTX Corp', weight: 4.2, change: 1.5, score: 76, volumeVsAvg: 1.1, peVsSector: -5, insiderActivity: 'none' },
      { ticker: 'BA', name: 'Boeing', weight: 3.8, change: -2.5, score: 45, volumeVsAvg: 2.1, peVsSector: -50, insiderActivity: 'none' },
      { ticker: 'DE', name: 'Deere & Co', weight: 3.5, change: -0.8, score: 68, volumeVsAvg: 1.0, peVsSector: -8, insiderActivity: 'none' },
      { ticker: 'UPS', name: 'UPS', weight: 3.2, change: -1.2, score: 58, volumeVsAvg: 1.3, peVsSector: -15, insiderActivity: 'sell' },
      { ticker: 'LMT', name: 'Lockheed Martin', weight: 3.0, change: 1.8, score: 80, volumeVsAvg: 1.0, peVsSector: 2, insiderActivity: 'none' },
      { ticker: 'ETN', name: 'Eaton Corp', weight: 2.8, change: 2.5, score: 82, volumeVsAvg: 1.4, peVsSector: 15, insiderActivity: 'buy' },
    ],
    correlations: [{ ticker: 'SPY', correlation: 0.88 }],
    macroSensitivity: [{ factor: 'GDP Growth', sensitivity: 'High', impact: 'Cyclical sector' }],
    industryTrends: [{ trend: 'Infrastructure Bill', impact: 'Positive', description: 'Multi-year spending' }],
    risks: [{ risk: 'Economic Slowdown', probability: 'Medium', impact: 'High' }],
    breakoutCandidate: { ticker: 'GE', name: 'GE Aerospace', score: 84, correlation: 0.62, reasons: ['Aerospace pure play'], entry: '$175-185', target: '$220 (+22%)', stop: '$160 (-10%)', riskReward: '2.2:1' },
    tradeIdeas: [{ strategy: 'Aerospace', trade: 'Long GE', thesis: 'Engine cycle', target: '+22%' }],
  },
  {
    id: '7', name: 'Materials', ticker: 'XLB', icon: 'Gem', price: 87.30, changePercent: 0.75,
    weekChange: 1.8, monthChange: 3.2, ytdChange: 5.1, momentum: 35, relativeStrength: 48,
    sentiment: 'neutral', beta: 1.15, marketCap: '$0.8T', spWeight: 2.4, companies: 28,
    description: 'Chemicals, Metals, Mining',
    verdict: { rating: 55, signal: 'NEUTRAL', summary: 'China recovery key catalyst. EV materials offer upside.' },
    etfs: [{ ticker: 'XLB', name: 'Materials Select', aum: '$5B' }],
    topHoldings: [
      { ticker: 'LIN', name: 'Linde', weight: 18.5, change: 1.2, score: 82, volumeVsAvg: 0.8, peVsSector: 25, insiderActivity: 'none' },
      { ticker: 'SHW', name: 'Sherwin-Williams', weight: 10.2, change: 0.8, score: 78, volumeVsAvg: 0.7, peVsSector: 30, insiderActivity: 'none' },
      { ticker: 'APD', name: 'Air Products', weight: 7.5, change: -0.5, score: 68, volumeVsAvg: 0.9, peVsSector: 5, insiderActivity: 'none' },
      { ticker: 'ECL', name: 'Ecolab', weight: 6.8, change: 1.5, score: 75, volumeVsAvg: 1.0, peVsSector: 15, insiderActivity: 'none' },
      { ticker: 'FCX', name: 'Freeport-McMoRan', weight: 6.2, change: 2.8, score: 76, volumeVsAvg: 1.8, peVsSector: -12, insiderActivity: 'buy' },
      { ticker: 'NEM', name: 'Newmont', weight: 5.5, change: 3.5, score: 72, volumeVsAvg: 2.2, peVsSector: -8, insiderActivity: 'none' },
      { ticker: 'NUE', name: 'Nucor', weight: 4.8, change: -1.2, score: 62, volumeVsAvg: 1.1, peVsSector: -20, insiderActivity: 'none' },
      { ticker: 'DOW', name: 'Dow Inc', weight: 4.2, change: -0.8, score: 55, volumeVsAvg: 1.0, peVsSector: -25, insiderActivity: 'sell' },
      { ticker: 'DD', name: 'DuPont', weight: 3.5, change: 0.5, score: 64, volumeVsAvg: 0.9, peVsSector: -5, insiderActivity: 'none' },
      { ticker: 'VMC', name: 'Vulcan Materials', weight: 3.2, change: 1.8, score: 74, volumeVsAvg: 1.2, peVsSector: 18, insiderActivity: 'none' },
    ],
    correlations: [{ ticker: 'DBC', correlation: 0.72 }],
    macroSensitivity: [{ factor: 'China Economy', sensitivity: 'High', impact: 'Largest commodity consumer' }],
    industryTrends: [{ trend: 'EV Battery Materials', impact: 'Positive', description: 'Copper, lithium demand' }],
    risks: [{ risk: 'China Slowdown', probability: 'Medium', impact: 'High' }],
    breakoutCandidate: { ticker: 'FCX', name: 'Freeport-McMoRan', score: 76, correlation: 0.58, reasons: ['Copper essential for EVs'], entry: '$42-45', target: '$55 (+25%)', stop: '$38 (-12%)', riskReward: '2.1:1' },
    tradeIdeas: [{ strategy: 'Copper Play', trade: 'Long FCX', thesis: 'EV demand', target: '+25%' }],
  },
  {
    id: '8', name: 'Utilities', ticker: 'XLU', icon: 'Lightbulb', price: 68.90, changePercent: -0.65,
    weekChange: -1.2, monthChange: -0.8, ytdChange: 1.2, momentum: -20, relativeStrength: 32,
    sentiment: 'bearish', beta: 0.45, marketCap: '$1.2T', spWeight: 2.5, companies: 31,
    description: 'Electric, Gas, Water Utilities',
    verdict: { rating: 48, signal: 'UNDERWEIGHT', summary: 'Rate sensitive sector underperforming. Data center demand offers select opportunities.' },
    etfs: [{ ticker: 'XLU', name: 'Utilities Select', aum: '$15B' }],
    topHoldings: [
      { ticker: 'NEE', name: 'NextEra Energy', weight: 15.2, change: -0.5, score: 75, volumeVsAvg: 0.9, peVsSector: 18, insiderActivity: 'none' },
      { ticker: 'SO', name: 'Southern Company', weight: 8.5, change: -0.3, score: 70, volumeVsAvg: 0.8, peVsSector: -5, insiderActivity: 'none' },
      { ticker: 'DUK', name: 'Duke Energy', weight: 7.8, change: -0.8, score: 68, volumeVsAvg: 0.7, peVsSector: -8, insiderActivity: 'none' },
      { ticker: 'CEG', name: 'Constellation Energy', weight: 6.5, change: 3.8, score: 85, volumeVsAvg: 2.5, peVsSector: 45, insiderActivity: 'buy' },
      { ticker: 'SRE', name: 'Sempra', weight: 5.2, change: 0.2, score: 65, volumeVsAvg: 0.8, peVsSector: -3, insiderActivity: 'none' },
      { ticker: 'AEP', name: 'American Electric', weight: 4.8, change: -0.5, score: 62, volumeVsAvg: 0.9, peVsSector: -10, insiderActivity: 'none' },
      { ticker: 'D', name: 'Dominion Energy', weight: 4.2, change: -1.2, score: 55, volumeVsAvg: 1.1, peVsSector: -15, insiderActivity: 'sell' },
      { ticker: 'PCG', name: 'PG&E Corp', weight: 3.8, change: 0.8, score: 58, volumeVsAvg: 1.0, peVsSector: -20, insiderActivity: 'none' },
      { ticker: 'VST', name: 'Vistra Corp', weight: 3.5, change: 5.2, score: 79, volumeVsAvg: 3.1, peVsSector: 35, insiderActivity: 'buy' },
      { ticker: 'XEL', name: 'Xcel Energy', weight: 3.2, change: -0.6, score: 60, volumeVsAvg: 0.7, peVsSector: -8, insiderActivity: 'none' },
    ],
    correlations: [{ ticker: 'TLT', correlation: 0.65 }],
    macroSensitivity: [{ factor: 'Interest Rates', sensitivity: 'High', impact: 'Bond proxy' }],
    industryTrends: [{ trend: 'Data Center Demand', impact: 'Positive', description: 'AI driving power needs' }],
    risks: [{ risk: 'Interest Rate Risk', probability: 'High', impact: 'High' }],
    breakoutCandidate: { ticker: 'VST', name: 'Vistra Corp', score: 79, correlation: 0.35, reasons: ['AI/Data center demand'], entry: '$115-125', target: '$155 (+28%)', stop: '$100 (-15%)', riskReward: '1.9:1' },
    tradeIdeas: [{ strategy: 'Data Center Power', trade: 'Long VST', thesis: 'AI power demand', target: '+28%' }],
  },
  {
    id: '9', name: 'Real Estate', ticker: 'XLRE', icon: 'Building2', price: 38.50, changePercent: 0.65,
    weekChange: 1.1, monthChange: 2.3, ytdChange: 3.4, momentum: 15, relativeStrength: 38,
    sentiment: 'neutral', beta: 0.85, marketCap: '$1.1T', spWeight: 2.3, companies: 31,
    description: 'REITs, Property Management',
    verdict: { rating: 52, signal: 'NEUTRAL', summary: 'Office headwinds offset by data center strength. Selective approach recommended.' },
    etfs: [{ ticker: 'XLRE', name: 'Real Estate Select', aum: '$6B' }],
    topHoldings: [
      { ticker: 'PLD', name: 'Prologis', weight: 12.5, change: 1.2, score: 82, volumeVsAvg: 1.0, peVsSector: 15, insiderActivity: 'none' },
      { ticker: 'AMT', name: 'American Tower', weight: 10.2, change: 0.5, score: 72, volumeVsAvg: 0.8, peVsSector: 8, insiderActivity: 'none' },
      { ticker: 'EQIX', name: 'Equinix', weight: 8.8, change: 2.8, score: 85, volumeVsAvg: 1.6, peVsSector: 42, insiderActivity: 'buy' },
      { ticker: 'CCI', name: 'Crown Castle', weight: 6.5, change: -1.5, score: 55, volumeVsAvg: 1.2, peVsSector: -12, insiderActivity: 'sell' },
      { ticker: 'PSA', name: 'Public Storage', weight: 5.8, change: 0.3, score: 70, volumeVsAvg: 0.7, peVsSector: 5, insiderActivity: 'none' },
      { ticker: 'SPG', name: 'Simon Property', weight: 5.2, change: 1.8, score: 68, volumeVsAvg: 1.1, peVsSector: -8, insiderActivity: 'none' },
      { ticker: 'O', name: 'Realty Income', weight: 4.8, change: -0.2, score: 72, volumeVsAvg: 0.9, peVsSector: -5, insiderActivity: 'none' },
      { ticker: 'WELL', name: 'Welltower', weight: 4.5, change: 1.5, score: 76, volumeVsAvg: 1.2, peVsSector: 10, insiderActivity: 'buy' },
      { ticker: 'DLR', name: 'Digital Realty', weight: 4.2, change: 3.2, score: 80, volumeVsAvg: 1.8, peVsSector: 28, insiderActivity: 'none' },
      { ticker: 'VICI', name: 'VICI Properties', weight: 3.5, change: 0.8, score: 74, volumeVsAvg: 0.8, peVsSector: -3, insiderActivity: 'none' },
    ],
    correlations: [{ ticker: 'TLT', correlation: 0.58 }],
    macroSensitivity: [{ factor: 'Interest Rates', sensitivity: 'High', impact: 'Cap rates expand' }],
    industryTrends: [{ trend: 'Data Centers', impact: 'Positive', description: 'AI driving demand' }],
    risks: [{ risk: 'Office Vacancy', probability: 'High', impact: 'Medium' }],
    breakoutCandidate: { ticker: 'EQIX', name: 'Equinix', score: 85, correlation: 0.42, reasons: ['Data center demand'], entry: '$880-920', target: '$1,100 (+22%)', stop: '$800 (-10%)', riskReward: '2.2:1' },
    tradeIdeas: [{ strategy: 'Data Center', trade: 'Long EQIX', thesis: 'AI infrastructure', target: '+22%' }],
  },
  {
    id: '10', name: 'Consumer Staples', ticker: 'XLP', icon: 'Wheat', price: 76.80, changePercent: -0.45,
    weekChange: -0.8, monthChange: 1.2, ytdChange: 2.8, momentum: 10, relativeStrength: 42,
    sentiment: 'neutral', beta: 0.55, marketCap: '$2.1T', spWeight: 6.2, companies: 38,
    description: 'Food, Beverage, Household',
    verdict: { rating: 55, signal: 'NEUTRAL', summary: 'Defensive play with modest growth. Costco stands out as quality compounder.' },
    etfs: [{ ticker: 'XLP', name: 'Consumer Staples Select', aum: '$18B' }],
    topHoldings: [
      { ticker: 'PG', name: 'Procter & Gamble', weight: 15.2, change: 0.5, score: 82, volumeVsAvg: 0.8, peVsSector: 10, insiderActivity: 'none' },
      { ticker: 'COST', name: 'Costco', weight: 12.8, change: 1.2, score: 85, volumeVsAvg: 1.0, peVsSector: 45, insiderActivity: 'none' },
      { ticker: 'KO', name: 'Coca-Cola', weight: 8.5, change: -0.3, score: 75, volumeVsAvg: 0.7, peVsSector: -2, insiderActivity: 'none' },
      { ticker: 'PEP', name: 'PepsiCo', weight: 7.8, change: -0.8, score: 72, volumeVsAvg: 0.9, peVsSector: -5, insiderActivity: 'none' },
      { ticker: 'WMT', name: 'Walmart', weight: 7.2, change: 0.8, score: 80, volumeVsAvg: 1.1, peVsSector: 15, insiderActivity: 'none' },
      { ticker: 'PM', name: 'Philip Morris', weight: 5.5, change: 1.5, score: 76, volumeVsAvg: 1.2, peVsSector: 8, insiderActivity: 'none' },
      { ticker: 'MO', name: 'Altria', weight: 3.8, change: 0.2, score: 60, volumeVsAvg: 0.8, peVsSector: -18, insiderActivity: 'none' },
      { ticker: 'CL', name: 'Colgate-Palmolive', weight: 3.5, change: -0.5, score: 68, volumeVsAvg: 0.7, peVsSector: 5, insiderActivity: 'none' },
      { ticker: 'MDLZ', name: 'Mondelez', weight: 3.2, change: 0.3, score: 70, volumeVsAvg: 0.8, peVsSector: -3, insiderActivity: 'none' },
      { ticker: 'TGT', name: 'Target', weight: 2.8, change: -1.5, score: 55, volumeVsAvg: 1.4, peVsSector: -22, insiderActivity: 'sell' },
    ],
    correlations: [{ ticker: 'XLU', correlation: 0.55 }],
    macroSensitivity: [{ factor: 'Inflation', sensitivity: 'Medium', impact: 'Can pass through prices' }],
    industryTrends: [{ trend: 'Private Label Growth', impact: 'Negative', description: 'Store brands gaining' }],
    risks: [{ risk: 'Private Label Competition', probability: 'High', impact: 'Medium' }],
    breakoutCandidate: { ticker: 'COST', name: 'Costco', score: 85, correlation: 0.48, reasons: ['Membership recurring revenue'], entry: '$920-960', target: '$1,150 (+22%)', stop: '$850 (-8%)', riskReward: '2.8:1' },
    tradeIdeas: [{ strategy: 'Quality Compounder', trade: 'Long COST', thesis: 'Membership moat', target: '+22%' }],
  },
  {
    id: '11', name: 'Communication', ticker: 'XLC', icon: 'Globe', price: 82.40, changePercent: 1.41,
    weekChange: 2.9, monthChange: 5.8, ytdChange: 9.2, momentum: 52, relativeStrength: 58,
    sentiment: 'bullish', beta: 1.02, marketCap: '$4.8T', spWeight: 8.8, companies: 24,
    description: 'Media, Telecom, Entertainment',
    verdict: { rating: 72, signal: 'OVERWEIGHT', summary: 'AI-driven ad efficiency boosting META and GOOGL. Strong earnings momentum.' },
    etfs: [{ ticker: 'XLC', name: 'Communication Services', aum: '$15B' }],
    topHoldings: [
      { ticker: 'META', name: 'Meta Platforms', weight: 22.5, change: 2.8, score: 88, volumeVsAvg: 1.3, peVsSector: 15, insiderActivity: 'none' },
      { ticker: 'GOOGL', name: 'Alphabet', weight: 20.8, change: 1.5, score: 84, volumeVsAvg: 1.1, peVsSector: 5, insiderActivity: 'none' },
      { ticker: 'NFLX', name: 'Netflix', weight: 8.5, change: 3.2, score: 82, volumeVsAvg: 1.6, peVsSector: 35, insiderActivity: 'sell' },
      { ticker: 'TMUS', name: 'T-Mobile', weight: 7.2, change: 0.8, score: 78, volumeVsAvg: 0.8, peVsSector: -5, insiderActivity: 'none' },
      { ticker: 'DIS', name: 'Walt Disney', weight: 5.5, change: -0.5, score: 62, volumeVsAvg: 1.2, peVsSector: -15, insiderActivity: 'none' },
      { ticker: 'CMCSA', name: 'Comcast', weight: 4.8, change: -1.2, score: 58, volumeVsAvg: 1.0, peVsSector: -22, insiderActivity: 'sell' },
      { ticker: 'VZ', name: 'Verizon', weight: 4.2, change: 0.2, score: 55, volumeVsAvg: 0.7, peVsSector: -28, insiderActivity: 'none' },
      { ticker: 'T', name: 'AT&T', weight: 3.8, change: -0.3, score: 52, volumeVsAvg: 0.8, peVsSector: -32, insiderActivity: 'none' },
      { ticker: 'CHTR', name: 'Charter Comms', weight: 2.8, change: -1.8, score: 48, volumeVsAvg: 1.3, peVsSector: -18, insiderActivity: 'none' },
      { ticker: 'EA', name: 'Electronic Arts', weight: 2.2, change: 1.5, score: 68, volumeVsAvg: 1.1, peVsSector: 8, insiderActivity: 'none' },
    ],
    correlations: [{ ticker: 'XLK', correlation: 0.82 }],
    macroSensitivity: [{ factor: 'Ad Spending', sensitivity: 'High', impact: 'Digital ads tied to economy' }],
    industryTrends: [{ trend: 'AI Integration', impact: 'Positive', description: 'AI improving targeting' }],
    risks: [{ risk: 'Regulation/Antitrust', probability: 'Medium', impact: 'High' }],
    breakoutCandidate: { ticker: 'META', name: 'Meta Platforms', score: 88, correlation: 0.72, reasons: ['AI driving ad efficiency'], entry: '$580-620', target: '$750 (+25%)', stop: '$520 (-12%)', riskReward: '2.1:1' },
    tradeIdeas: [{ strategy: 'AI + Ads', trade: 'Long META', thesis: 'AI improving ROAS', target: '+25%' }],
  },
];