/**
 * Type definitions for the SEO ticker data pipeline.
 *
 * Two JSON sources:
 *  - ticker-universe.json  — lightweight list of all 2,500 tickers (always present)
 *  - seo-tickers.json      — enriched data (price, fundamentals, news) generated by the script
 */

// ---------------------------------------------------------------------------
// ticker-universe.json
// ---------------------------------------------------------------------------

export interface TickerUniverseEntry {
  ticker: string;
  name: string;
  sector: string | null;
  industry: string | null;
  type: 'stock' | 'etf';
}

export interface TickerUniverseFile {
  generated_at: string;
  count: number;
  source: string;
  tickers: TickerUniverseEntry[];
}

// ---------------------------------------------------------------------------
// seo-tickers.json
// ---------------------------------------------------------------------------

export interface SeoTickerPrice {
  last: number | null;
  change_pct: number | null;
  as_of: string | null;
}

export interface SeoTickerFundamentals {
  marketCap: null;
  revenue: number | null;
  netIncome: number | null;
  eps: number | null;
  pe: number | null;
  roe: number | null;
  debtToEquity: number | null;
  dividendPerShare: number | null;
  fundamentalsPrice: number | null;
}

export interface SeoTickerNewsItem {
  title: string | null;
  source: string | null;
  url: string | null;
  published_at: string | null;
}

export interface SeoTickerData {
  ticker: string;
  name: string;
  sector: string | null;
  industry: string | null;
  type: 'stock' | 'etf';
  description: string | null;
  price: SeoTickerPrice;
  fundamentals: SeoTickerFundamentals;
  news: SeoTickerNewsItem[];
  fetched_at: string;
}

export interface SeoTickersFile {
  generated_at: string;
  count: number;
  tickers: Record<string, SeoTickerData>;
}
