// =====================================================
// 🔗 HOOK: useSectorAnalysis
// =====================================================
// Location: src/hooks/useSectorAnalysis.ts
//
// "COMPUTE ONCE, SERVE 10,000" - Client Side
//
// Reads from sector_snapshots + top_down_macro_snapshot.
// ZERO AI calls. Just a simple SELECT query.
//
// ⚠️ FIELD MAPPING:
//   DB: verdict           → Component: sector_verdict
//   DB: ai_generated_at   → Component: generated_at
//   DB: ai_commentary     → Component: ai_commentary (string)
//
// staleTime = 5 minutes (cache updates 4x/day)
// =====================================================

import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/lib/supabase';

// ============================================
// TYPES
// ============================================

export interface MacroSnapshot {
  regime: string;
  regime_label: string;
  risk_level: string;
  fed_policy: string;
  rate_direction: string;
  gdp_outlook: string;
  inflation_trend: string;
  employment_outlook: string;
  ism_pmi: number;
  ism_direction: string;
  ism_key_signals: string[];
  ism_report_month: string;
  favored_sectors: string[];
  avoid_sectors: string[];
  rotation_theme: string;
  ai_macro_narrative: string;
  generated_at: string;
}

export interface SectorSnapshot {
  // Identity
  id: string;
  sector_name: string;
  ticker: string;

  // Price
  price: number;
  change_percent: number;
  week_change: number;
  month_change: number;
  ytd_change: number;

  // Metrics
  momentum: number;
  relative_strength: number;
  sentiment: string;
  beta: number;
  market_cap: string;
  sp_weight: number;

  // Data
  top_holdings: any[];
  sub_sectors: any[];
  vs_market: any[];
  fundamentals: any;
  money_flow: any;
  correlations: any[];
  correlation_breakers: any[];
  pairs_trades: any[];
  intra_sector_correlation: any;
  macro_sensitivity: any[];
  risks: any[];
  breakout_candidate: any;

  // DB column names (raw from Supabase)
  verdict: any;
  ai_generated_at: string;

  // Mapped names (for trade_ideas component)
  sector_verdict?: any;
  generated_at?: string;

  // Earnings Calendar (cron-fetched from Yahoo Finance, FREE)
  earnings_calendar: Array<{
    date: string;
    ticker: string;
    company: string;
    estimate: number | null;
    whisper: number | null;
    impact: 'High' | 'Medium' | 'Low';
    time?: string;
  }>;

  // Macro + ISM (JSONB columns)
  macro_regime: {
    regime: string;
    regimeLabel: string;
    riskLevel: string;
    fedPolicy: string;
    rotationTheme: string;
    narrative: string;
  };
  ism_context: {
    pmi: number;
    direction: string;
    keySignals: string[];
    month: string;
    newOrders: number;
    employment: number;
    prices: number;
    backlog: number;
    production?: number;
    demandSignal?: string;
    pricingPowerSignal?: string;
    laborMarketSignal?: string;
    executiveQuotes?: Array<{
      industry: string;
      comment: string;
      sentiment: string;
    }>;
    ismVerdict?: string;
  };
  top_down_flow: {
    macroNarrative: string;
    sectorThesis: string;
    ismConnection: string;
    stockPicks: string[];
  };
  rotation_signal: {
    strength: string;
    catalyst: string;
    ismDriver: string;
  };
  allocation_guide: {
    recommendedWeight: string;
    conviction: string;
    riskProfile: string;
  };

  // Trade Ideas
  trade_ideas: Array<{
    strategy: string;
    direction: 'long' | 'short';
    ticker: string;
    thesis: string;
    ismBacking: string;
    entry: string;
    target: string;
    stop: string;
    conviction: number;
    riskReward: string;
    timeHorizon: string;
    risks: string[];
  }>;

  // AI (TEXT columns)
  ai_commentary: string;
  ai_bull_case: string;
  ai_bear_case: string;
  ai_key_trade: string;

  // Risk Analysis (JSONB — generated by cron, served from cache)
  risk_analysis: {
    overallRiskScore: number;
    riskLevel: string;
    riskSummary: string;
    macroRisks: Array<{
      risk: string;
      severity: string;
      why: string;
      whatsChanging: string;
      affectedLeaders: string[];
    }>;
    sectorRisks: Array<{
      risk: string;
      severity: string;
      why: string;
      trendShift: string;
      affectedLeaders: string[];
    }>;
    leaderContagion: Array<{
      ticker: string;
      name: string;
      sectorWeight: string;
      risk: string;
      catalyst: string;
      contagionLevel: string;
    }>;
    trendChanges: Array<{
      indicator: string;
      direction: string;
      detail: string;
      actionable: string;
    }>;
    exitTriggers: string[];
    hedgeIdea: string;
  };

  // Refresh
  refresh_session: string;
  refresh_type: string;
  data_timestamp: string;
  updated_at: string;
}

// ============================================
// DB → Component field transform
// Maps DB column names to what trade_ideas component expects
// ============================================

function transformSnapshot(row: any): SectorSnapshot {
  return {
    ...row,
    // DB: verdict → Component: sector_verdict
    sector_verdict: row.verdict,
    // DB: ai_generated_at → Component: generated_at
    generated_at: row.ai_generated_at,
  };
}

// ============================================
// FETCH FUNCTIONS
// ============================================

async function fetchAllSectorAnalysis(): Promise<{
  macro: MacroSnapshot | null;
  sectors: SectorSnapshot[];
}> {
  const [macroResult, sectorsResult] = await Promise.all([
    supabase
      .from('top_down_macro_snapshot')
      .select('*')
      .order('generated_at', { ascending: false })
      .limit(1)
      .single(),
    supabase
      .from('sector_snapshots')
      .select('*')
      .order('sector_name'),
  ]);

  return {
    macro: macroResult.data || null,
    sectors: (sectorsResult.data || []).map(transformSnapshot),
  };
}

async function fetchSectorAnalysis(sectorId: string): Promise<SectorSnapshot | null> {
  const { data, error } = await supabase
    .from('sector_snapshots')
    .select('*')
    .eq('id', sectorId)
    .single();

  if (error || !data) return null;
  return transformSnapshot(data);
}

async function fetchMacroSnapshot(): Promise<MacroSnapshot | null> {
  const { data, error } = await supabase
    .from('top_down_macro_snapshot')
    .select('*')
    .order('generated_at', { ascending: false })
    .limit(1)
    .single();

  if (error || !data) return null;
  return data;
}

// ============================================
// HOOKS
// ============================================

export function useAllSectorAnalysis() {
  return useQuery({
    queryKey: ['sector-analysis', 'all'],
    queryFn: fetchAllSectorAnalysis,
    staleTime: 5 * 60 * 1000,
    gcTime: 30 * 60 * 1000,
    refetchOnWindowFocus: false,
    retry: 2,
  });
}

export function useSectorAnalysis(sectorId: string) {
  return useQuery({
    queryKey: ['sector-analysis', sectorId],
    queryFn: () => fetchSectorAnalysis(sectorId),
    staleTime: 5 * 60 * 1000,
    gcTime: 30 * 60 * 1000,
    refetchOnWindowFocus: false,
    retry: 2,
    enabled: !!sectorId,
  });
}

export function useMacroSnapshot() {
  return useQuery({
    queryKey: ['macro-snapshot'],
    queryFn: fetchMacroSnapshot,
    staleTime: 5 * 60 * 1000,
    gcTime: 30 * 60 * 1000,
    refetchOnWindowFocus: false,
    retry: 2,
  });
}

/**
 * Helper: Convert sector name → sector_snapshots.id
 */
export function sectorNameToId(name: string): string {
  const map: Record<string, string> = {
    'Technology': 'technology',
    'Healthcare': 'healthcare',
    'Financials': 'financials',
    'Energy': 'energy',
    'Consumer Disc.': 'consumer_disc',
    'Consumer Discretionary': 'consumer_disc',
    'Industrials': 'industrials',
    'Materials': 'materials',
    'Utilities': 'utilities',
    'Real Estate': 'real_estate',
    'Consumer Staples': 'consumer_staples',
    'Communication': 'communication',
    'Communication Services': 'communication',
  };
  return map[name] || name.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '');
}