// ============================================================
// src/pages/app/forex/components/AIMarketBrief.tsx
// AI-generated forex market commentary tile.
// Gold-on-black, English only. Fetch-once (no poll interval).
// ============================================================

import { useForexCommentary } from '../_shared/hooks';
import {
  GlassCard,
  SectionHeader,
  GlassStatSkeleton,
  EmptyState,
} from '@/pages/app/crypto/_shared/GlassUI';

export default function AIMarketBrief() {
  const { data, loading } = useForexCommentary();

  // Loading state — show a taller skeleton block
  if (loading) {
    return (
      <GlassCard padding="lg">
        <SectionHeader title="AI Market Brief" />
        <div className="animate-pulse space-y-3">
          <div className="h-4 w-full bg-white/10 rounded" />
          <div className="h-4 w-[90%] bg-white/10 rounded" />
          <div className="h-4 w-[80%] bg-white/10 rounded" />
          <div className="h-4 w-[60%] bg-white/[0.06] rounded" />
        </div>
      </GlassCard>
    );
  }

  // Unavailable or empty commentary
  const isUnavailable =
    !data ||
    data.source === 'unavailable' ||
    !data.commentary ||
    data.commentary.trim() === '';

  if (isUnavailable) {
    return (
      <GlassCard padding="lg">
        <SectionHeader title="AI Market Brief" />
        <EmptyState
          icon="📰"
          title="Market brief will appear here."
          description="The AI commentary will be available once the market session begins."
        />
      </GlassCard>
    );
  }

  // Format generated_at for display (e.g. "Jun 4, 2026, 14:30 UTC")
  const generatedLabel = (() => {
    if (!data.generated_at) return null;
    try {
      return new Intl.DateTimeFormat('en-US', {
        month: 'short',
        day: 'numeric',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
        timeZone: 'UTC',
        timeZoneName: 'short',
      }).format(new Date(data.generated_at));
    } catch {
      return data.generated_at;
    }
  })();

  return (
    <GlassCard padding="lg">
      <SectionHeader title="AI Market Brief" />

      {/* Commentary body */}
      <p className="text-sm leading-relaxed text-white/80 whitespace-pre-wrap">
        {data.commentary}
      </p>

      {/* Footnote */}
      <div className="mt-4 flex flex-wrap items-center gap-x-3 gap-y-1 border-t border-white/[0.06] pt-3">
        <span className="text-[11px] font-medium text-amber-400/70 uppercase tracking-wide">
          Generated by FINOTAUR AI
        </span>
        {generatedLabel && (
          <span className="text-[11px] text-white/30">{generatedLabel}</span>
        )}
      </div>
    </GlassCard>
  );
}
