import { Card, Eyebrow } from '@/components/ds/Card';

export default function MarketCommentaryPlaceholder() {
  return (
    <Card variant="featured" className="h-full">
      <div className="flex flex-col gap-ds-3">
        <div className="flex items-center justify-between">
          <Eyebrow>What's Moving Today</Eyebrow>
          <span className="font-sans text-[10px] uppercase tracking-[1.5px] text-ink-tertiary">Coming Soon</span>
        </div>
        <p className="font-sans text-[14px] leading-relaxed text-ink-secondary">
          FX market commentary — generated by Claude Haiku, refreshed once per day, shared across all visitors.
          Will summarize the day's USD strength, key pair moves, and upcoming calendar catalysts in 2-3 sentences.
        </p>
        <div className="text-[11px] text-ink-tertiary tracking-[1px] uppercase">Wires up next sprint</div>
      </div>
    </Card>
  );
}
