// tabs/AITab.tsx
// =====================================================
// 🤖 AI MACRO INTELLIGENCE TAB
// AI-powered analysis combining all data sources into
// actionable intelligence for traders & investors.
//
// EFFICIENCY FOR 10K USERS:
// ✅ ALL AI calls go through backend (shared cache)
// ✅ GET /ai-analysis = zero cost (reads cache only)
// ✅ POST /ai-generate/:section = 1 AI call for ALL users
// ✅ No direct Anthropic/OpenAI calls from client
// ✅ Signal Dashboard = pure data computation (no AI)
// ✅ Key Movers = pure data computation (no AI)
// ✅ LazySection = only render what's visible
//
// COST: 10K users × 3 sections = 3 AI calls per hour (not 30K)
// =====================================================

import React, { memo, useMemo, useState, useCallback, useRef, useEffect } from 'react';
import {
  Brain, Sparkles, TrendingUp, TrendingDown, Activity,
  RefreshCw, AlertTriangle, Shield, Target, Zap,
  BarChart2, ChevronDown, Clock, DollarSign,
  ArrowUpRight, ArrowDownRight, Minus, Layers,
  CheckCircle, XCircle, AlertCircle, Eye,
  Crosshair, PieChart, ArrowRight, Lightbulb
} from 'lucide-react';
import {
  Card, SectionHeader, Badge, ProgressBar, LazySection,
  cn, SectionSkeleton, MiniChart, StatBox
} from '../shared/ui';
import {
  useOverview, useGlobal, useFedData,
  fetchAIAnalysis, generateAISection,
  type OverviewData, type GlobalData, type FedData,
  type IndicatorData, type RegimeData, type AIResult
} from '../shared/api';

// =====================================================
// SERVER AI HOOK (uses backend cache, NOT client AI)
// =====================================================

interface UseServerAIResult {
  response: string | null;
  isLoading: boolean;
  error: string | null;
  generate: () => void;
  fromCache: boolean;
  ageMinutes: number | null;
  rateLimited: boolean;
}

function useServerAI(section: 'regime' | 'positioning' | 'risk'): UseServerAIResult {
  const [response, setResponse] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [fromCache, setFromCache] = useState(false);
  const [ageMinutes, setAgeMinutes] = useState<number | null>(null);
  const [rateLimited, setRateLimited] = useState(false);
  const mountedRef = useRef(true);

  useEffect(() => {
    mountedRef.current = true;
    return () => { mountedRef.current = false; };
  }, []);

  // Load from server cache on mount (zero cost)
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const cached = await fetchAIAnalysis();
        if (cancelled || !mountedRef.current) return;
        const sectionData = cached?.[section];
        if (sectionData?.analysis) {
          setResponse(sectionData.analysis);
          setFromCache(true);
          setAgeMinutes(sectionData.ageMinutes ?? null);
        }
      } catch {
        // Silent — cache miss is fine
      }
    })();
    return () => { cancelled = true; };
  }, [section]);

  // Generate (calls backend POST, which calls OpenAI once for all users)
  const generate = useCallback(async () => {
    if (isLoading) return;
    setIsLoading(true);
    setError(null);
    setRateLimited(false);

    try {
      const result: AIResult = await generateAISection(section);
      if (!mountedRef.current) return;

      if (result.rateLimited) {
        setRateLimited(true);
        setError(`Rate limited. Try again in ${(result as any).retryAfterSeconds || 60}s.`);
        setIsLoading(false);
        return;
      }

      if (result.analysis) {
        setResponse(result.analysis);
        setFromCache(result.cached);
        setAgeMinutes(result.ageMinutes ?? 0);
      }
    } catch (err: any) {
      if (mountedRef.current) {
        setError(err.message || 'AI analysis failed');
      }
    } finally {
      if (mountedRef.current) setIsLoading(false);
    }
  }, [section, isLoading]);

  return { response, isLoading, error, generate, fromCache, ageMinutes, rateLimited };
}

// =====================================================
// AI SECTION CARD (reusable)
// =====================================================

const AISectionCard = memo(({
  icon: Icon,
  title,
  subtitle,
  response,
  isLoading,
  error,
  fromCache,
  ageMinutes,
  rateLimited,
  onGenerate,
  autoGenerated = false,
  accentColor = '#C9A646',
}: {
  icon: React.ElementType;
  title: string;
  subtitle: string;
  response: string | null;
  isLoading: boolean;
  error: string | null;
  fromCache: boolean;
  ageMinutes: number | null;
  rateLimited: boolean;
  onGenerate: () => void;
  autoGenerated?: boolean;
  accentColor?: string;
}) => {
  return (
    <Card highlight={!!response}>
      <div className="relative p-6">
        {response && (
          <div className="absolute top-0 left-0 w-1 h-full" style={{
            background: `linear-gradient(to bottom, ${accentColor}, ${accentColor}40, transparent)`
          }} />
        )}

        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-3">
            <div
              className="w-10 h-10 rounded-xl flex items-center justify-center"
              style={{ background: `${accentColor}15`, border: `1px solid ${accentColor}30` }}
            >
              <Icon className="w-5 h-5" style={{ color: accentColor }} />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-white">{title}</h3>
              <p className="text-xs text-[#6B6B6B]">{subtitle}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {fromCache && ageMinutes != null && (
              <span className="text-[10px] text-[#6B6B6B] flex items-center gap-1">
                <Clock className="w-3 h-3" /> {ageMinutes < 1 ? 'Just now' : `${ageMinutes}m ago`}
              </span>
            )}
            <button
              onClick={onGenerate}
              disabled={isLoading || rateLimited}
              className={cn(
                "flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-medium transition-all",
                isLoading || rateLimited
                  ? "text-[#6B6B6B] cursor-not-allowed"
                  : response
                    ? "text-[#8B8B8B] hover:text-[#C9A646]"
                    : "text-black"
              )}
              style={!response && !isLoading ? {
                background: `linear-gradient(135deg, ${accentColor}, #F4D97B)`
              } : {
                background: 'rgba(255,255,255,0.05)',
                border: '1px solid rgba(201,166,70,0.15)'
              }}
            >
              {isLoading ? (
                <>
                  <div className="w-3 h-3 border-2 border-current border-t-transparent rounded-full animate-spin" />
                  Analyzing...
                </>
              ) : response ? (
                <>
                  <RefreshCw className="w-3 h-3" /> Refresh
                </>
              ) : (
                <>
                  <Sparkles className="w-3 h-3" /> Generate
                </>
              )}
            </button>
          </div>
        </div>

        {/* Error State */}
        {error && (
          <div className="p-4 rounded-xl bg-[#EF4444]/5 border border-[#EF4444]/20 mb-4">
            <p className="text-xs text-[#EF4444] font-semibold mb-1">
              {rateLimited ? 'Rate Limited' : 'Analysis Failed'}
            </p>
            <p className="text-xs text-[#8B8B8B]">{error}</p>
            {!rateLimited && (
              <button
                onClick={onGenerate}
                className="mt-2 text-xs text-[#C9A646] hover:text-[#F4D97B]"
              >
                Try Again →
              </button>
            )}
          </div>
        )}

        {/* Loading State */}
        {isLoading && !response && (
          <div className="space-y-3">
            <div className="h-4 rounded bg-white/5 animate-pulse" style={{ width: '90%' }} />
            <div className="h-4 rounded bg-white/5 animate-pulse" style={{ width: '75%' }} />
            <div className="h-4 rounded bg-white/5 animate-pulse" style={{ width: '85%' }} />
            <div className="h-4 rounded bg-white/5 animate-pulse" style={{ width: '60%' }} />
            <div className="h-4 rounded bg-white/5 animate-pulse" style={{ width: '70%' }} />
          </div>
        )}

        {/* Response */}
        {response && (
          <div className="p-5 rounded-xl" style={{ background: `${accentColor}08`, border: `1px solid ${accentColor}20` }}>
            <p className="text-sm text-[#E8DCC4] leading-relaxed whitespace-pre-wrap">{response}</p>
          </div>
        )}

        {/* Empty State */}
        {!response && !isLoading && !error && (
          <div className="py-8 text-center">
            <Icon className="w-8 h-8 mx-auto mb-3" style={{ color: `${accentColor}40` }} />
            <p className="text-sm text-[#6B6B6B] mb-1">
              {autoGenerated ? 'Waiting for data...' : 'Click Generate to run AI analysis'}
            </p>
            <p className="text-[10px] text-[#4B4B4B]">
               Analysis based on live FRED & Yahoo Finance data
            </p>
          </div>
        )}
      </div>
    </Card>
  );
});
AISectionCard.displayName = 'AISectionCard';

// =====================================================
// DATA HEALTH DASHBOARD (shows what AI is analyzing)
// Pure data — no AI cost
// =====================================================

const DataHealthDashboard = memo(({ overview, global, fed }: {
  overview: OverviewData;
  global: GlobalData | null;
  fed: FedData | null;
}) => {
  const stats = useMemo(() => {
    const indicators = overview.indicators;
    const improving = indicators.filter(i => i.trend === 'improving').length;
    const declining = indicators.filter(i => i.trend === 'declining').length;
    const stable = indicators.length - improving - declining;
    return { improving, declining, stable, total: indicators.length };
  }, [overview]);

  return (
    <Card>
      <div className="p-6">
        <SectionHeader
          icon={Activity}
          title="Live Data Feed"
          subtitle="What the AI is analyzing right now"
        />

        <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-3">
          {/* Regime */}
          <div className="p-3 rounded-xl" style={{ background: 'rgba(201,166,70,0.05)', border: '1px solid rgba(201,166,70,0.2)' }}>
            <p className="text-[10px] text-[#6B6B6B] mb-1">Regime</p>
            <p className="text-sm font-bold text-[#C9A646]">{overview.regime.stage}</p>
            <p className="text-[10px] text-[#6B6B6B]">{overview.regime.confidence}% conf</p>
          </div>

          {/* Fed Rate */}
          <div className="p-3 rounded-xl bg-white/[0.03]">
            <p className="text-[10px] text-[#6B6B6B] mb-1">Fed Funds</p>
            <p className="text-sm font-bold text-white">{fed?.currentRate || overview.fed.currentRate}%</p>
            <p className="text-[10px] text-[#6B6B6B]">
              {fed?.yieldCurve != null ? `YC: ${fed.yieldCurve > 0 ? '+' : ''}${fed.yieldCurve.toFixed(2)}%` : ''}
            </p>
          </div>

          {/* Recession Prob */}
          <div className="p-3 rounded-xl bg-white/[0.03]">
            <p className="text-[10px] text-[#6B6B6B] mb-1">Recession Prob</p>
            <p className={cn("text-sm font-bold",
              overview.regime.recessionProbability < 25 ? 'text-[#22C55E]' :
              overview.regime.recessionProbability < 50 ? 'text-[#F59E0B]' : 'text-[#EF4444]'
            )}>{overview.regime.recessionProbability}%</p>
            <p className="text-[10px] text-[#6B6B6B]">12-month</p>
          </div>

          {/* Indicators Health */}
          <div className="p-3 rounded-xl bg-white/[0.03]">
            <p className="text-[10px] text-[#6B6B6B] mb-1">Indicators</p>
            <p className="text-sm font-bold text-white">
              <span className="text-[#22C55E]">{stats.improving}</span>
              <span className="text-[#6B6B6B]">/</span>
              <span className="text-[#F59E0B]">{stats.stable}</span>
              <span className="text-[#6B6B6B]">/</span>
              <span className="text-[#EF4444]">{stats.declining}</span>
            </p>
            <p className="text-[10px] text-[#6B6B6B]">↑ / → / ↓</p>
          </div>

          {/* DXY */}
          {global?.dxy && (
            <div className="p-3 rounded-xl bg-white/[0.03]">
              <p className="text-[10px] text-[#6B6B6B] mb-1">DXY</p>
              <p className="text-sm font-bold text-white">{global.dxy.value}</p>
              <p className={cn("text-[10px] font-medium",
                global.dxy.change > 0 ? 'text-[#22C55E]' : global.dxy.change < 0 ? 'text-[#EF4444]' : 'text-[#F59E0B]'
              )}>
                {global.dxy.change > 0 ? '+' : ''}{global.dxy.change.toFixed(2)}%
              </p>
            </div>
          )}

          {/* Score */}
          <div className="p-3 rounded-xl bg-white/[0.03]">
            <p className="text-[10px] text-[#6B6B6B] mb-1">Regime Score</p>
            <p className="text-sm font-bold text-white">{overview.regime.score}/100</p>
            <ProgressBar
              value={overview.regime.score}
              color={overview.regime.score > 60 ? '#22C55E' : overview.regime.score > 40 ? '#F59E0B' : '#EF4444'}
              className="mt-1"
            />
          </div>
        </div>
      </div>
    </Card>
  );
});
DataHealthDashboard.displayName = 'DataHealthDashboard';

// =====================================================
// QUICK SIGNALS (non-AI, computed from data — zero cost)
// =====================================================

const QuickSignals = memo(({ overview, fed }: {
  overview: OverviewData;
  fed: FedData | null;
}) => {
  const signals = useMemo(() => {
    const { indicators, regime } = overview;
    const result: { label: string; signal: 'bullish' | 'bearish' | 'neutral'; detail: string }[] = [];

    // Yield Curve
    if (fed?.yieldCurve != null) {
      result.push({
        label: 'Yield Curve',
        signal: fed.yieldCurve > 0.5 ? 'bullish' : fed.yieldCurve > 0 ? 'neutral' : 'bearish',
        detail: fed.yieldCurve > 0.5 ? 'Steep positive — expansion'
              : fed.yieldCurve > 0 ? 'Normalizing'
              : 'Inverted — recession signal',
      });
    }

    // Regime
    result.push({
      label: 'Economic Regime',
      signal: regime.stageIndex <= 2 ? 'bullish' : regime.stageIndex === 3 ? 'neutral' : 'bearish',
      detail: `${regime.stage} (${regime.confidence}% confidence)`,
    });

    // Recession Probability
    result.push({
      label: 'Recession Risk',
      signal: regime.recessionProbability < 20 ? 'bullish' : regime.recessionProbability < 40 ? 'neutral' : 'bearish',
      detail: `${regime.recessionProbability}% probability (12-month)`,
    });

    // Manufacturing
    const ism = indicators.find(i => i.id === 'ism-mfg' || i.id === 'ism_mfg');
    if (ism) {
      result.push({
        label: 'Manufacturing',
        signal: ism.value >= 52 ? 'bullish' : ism.value >= 48 ? 'neutral' : 'bearish',
        detail: `ISM ${ism.value} (${ism.trend})`,
      });
    }

    // Inflation
    const cpi = indicators.find(i => i.id === 'cpi');
    if (cpi) {
      result.push({
        label: 'Inflation',
        signal: cpi.trend === 'declining' ? 'bullish' : cpi.trend === 'stable' ? 'neutral' : 'bearish',
        detail: `CPI ${cpi.value}${cpi.unit} (${cpi.trend})`,
      });
    }

    // Labor Market
    const nfp = indicators.find(i => i.id === 'nfp');
    if (nfp) {
      result.push({
        label: 'Labor Market',
        signal: nfp.trend === 'improving' ? 'bullish' : nfp.trend === 'stable' ? 'neutral' : 'bearish',
        detail: `NFP ${nfp.value}${nfp.unit} (${nfp.trend})`,
      });
    }

    // Fed Policy
    const cutsCount = fed?.meetings?.filter(m => m.decision === 'cut').length || 0;
    result.push({
      label: 'Fed Policy',
      signal: cutsCount >= 2 ? 'bullish' : cutsCount >= 1 ? 'neutral' : 'bearish',
      detail: `${cutsCount} cuts priced, rate ${fed?.currentRate || overview.fed.currentRate}%`,
    });

    return result;
  }, [overview, fed]);

  const bullishCount = signals.filter(s => s.signal === 'bullish').length;
  const bearishCount = signals.filter(s => s.signal === 'bearish').length;
  const overallSignal = bullishCount > bearishCount ? 'RISK-ON' : bearishCount > bullishCount ? 'RISK-OFF' : 'MIXED';
  const overallColor = overallSignal === 'RISK-ON' ? '#22C55E' : overallSignal === 'RISK-OFF' ? '#EF4444' : '#F59E0B';

  return (
    <Card>
      <div className="p-6">
        <SectionHeader
          icon={Crosshair}
          title="Signal Dashboard"
          subtitle="Real-time macro signals — no AI, pure data"
          action={
            <div className="flex items-center gap-2">
              <span className="text-xs text-[#6B6B6B]">Overall:</span>
              <span className="text-sm font-bold px-3 py-1 rounded-lg" style={{
                color: overallColor,
                background: `${overallColor}10`,
                border: `1px solid ${overallColor}30`
              }}>
                {overallSignal}
              </span>
            </div>
          }
        />

        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
          {signals.map((sig, idx) => {
            const color = sig.signal === 'bullish' ? '#22C55E' : sig.signal === 'bearish' ? '#EF4444' : '#F59E0B';
            const SigIcon = sig.signal === 'bullish' ? ArrowUpRight : sig.signal === 'bearish' ? ArrowDownRight : Minus;

            return (
              <div
                key={idx}
                className="p-3 rounded-xl transition-colors"
                style={{ background: `${color}05`, border: `1px solid ${color}15` }}
              >
                <div className="flex items-center justify-between mb-2">
                  <span className="text-[10px] text-[#6B6B6B] uppercase tracking-wider">{sig.label}</span>
                  <SigIcon className="w-3.5 h-3.5" style={{ color }} />
                </div>
                <p className="text-xs font-semibold uppercase mb-1" style={{ color }}>
                  {sig.signal}
                </p>
                <p className="text-[10px] text-[#8B8B8B]">{sig.detail}</p>
              </div>
            );
          })}
        </div>

        {/* Signal Bar */}
        <div className="mt-4 p-3 rounded-lg bg-white/[0.02]">
          <div className="flex items-center justify-between mb-2">
            <span className="text-xs text-[#6B6B6B]">Bull / Bear Ratio</span>
            <span className="text-xs text-[#8B8B8B]">
              {bullishCount} bullish · {signals.length - bullishCount - bearishCount} neutral · {bearishCount} bearish
            </span>
          </div>
          <div className="h-2 bg-white/10 rounded-full overflow-hidden flex">
            <div
              className="h-full transition-all duration-700"
              style={{
                width: `${(bullishCount / signals.length) * 100}%`,
                background: '#22C55E'
              }}
            />
            <div
              className="h-full transition-all duration-700"
              style={{
                width: `${((signals.length - bullishCount - bearishCount) / signals.length) * 100}%`,
                background: '#F59E0B'
              }}
            />
            <div
              className="h-full transition-all duration-700"
              style={{
                width: `${(bearishCount / signals.length) * 100}%`,
                background: '#EF4444'
              }}
            />
          </div>
        </div>
      </div>
    </Card>
  );
});
QuickSignals.displayName = 'QuickSignals';

// =====================================================
// KEY MOVERS (top changing indicators — no AI cost)
// =====================================================

const KeyMovers = memo(({ indicators }: { indicators: IndicatorData[] }) => {
  const movers = useMemo(() => {
    return [...indicators]
      .filter(i => i.impact === 'high' && i.change !== 0)
      .sort((a, b) => Math.abs(b.change) - Math.abs(a.change))
      .slice(0, 6);
  }, [indicators]);

  if (movers.length === 0) return null;

  return (
    <Card>
      <div className="p-6">
        <SectionHeader
          icon={Zap}
          title="Top Movers"
          subtitle="High-impact indicators with biggest changes"
        />

        <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
          {movers.map((ind) => {
            const color = ind.trend === 'improving' ? '#22C55E' : ind.trend === 'declining' ? '#EF4444' : '#F59E0B';
            const MoverIcon = ind.trend === 'improving' ? ArrowUpRight : ind.trend === 'declining' ? ArrowDownRight : Minus;

            return (
              <div key={ind.id} className="p-4 rounded-xl bg-white/[0.03] hover:bg-white/[0.05] transition-colors">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-xs text-[#6B6B6B]">{ind.shortName}</span>
                  <Badge variant={ind.trend === 'improving' ? 'success' : ind.trend === 'declining' ? 'danger' : 'warning'}>
                    {ind.trend === 'improving' ? '↑' : ind.trend === 'declining' ? '↓' : '→'}
                  </Badge>
                </div>
                <div className="flex items-baseline gap-2 mb-1">
                  <span className="text-xl font-bold text-white">{ind.value}</span>
                  <span className="text-xs text-[#6B6B6B]">{ind.unit}</span>
                </div>
                <div className="flex items-center gap-1">
                  <MoverIcon className="w-3 h-3" style={{ color }} />
                  <span className="text-xs font-medium" style={{ color }}>
                    {ind.change > 0 ? '+' : ''}{ind.change}{ind.unit}
                  </span>
                  <span className="text-[10px] text-[#6B6B6B]">vs prior</span>
                </div>
                {ind.historicalData && ind.historicalData.length > 2 && (
                  <div className="mt-2 h-8">
                    <MiniChart data={ind.historicalData} color={color} height={32} />
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </Card>
  );
});
KeyMovers.displayName = 'KeyMovers';

// =====================================================
// MAIN AI TAB
// =====================================================

function AITab() {
  const { data: overview, isLoading: loadingOverview, error: errorOverview, refresh: refreshOverview } = useOverview();
  const { data: global } = useGlobal();
  const { data: fed } = useFedData();

  // Server-side AI hooks (all go through backend cache)
  const regime = useServerAI('regime');
  const positioning = useServerAI('positioning');
  const risk = useServerAI('risk');

  // Auto-generate regime analysis when data is ready and no cached response
  useEffect(() => {
    if (overview && !regime.response && !regime.isLoading && !regime.error) {
      regime.generate();
    }
  }, [overview]); // eslint-disable-line react-hooks/exhaustive-deps

  if (errorOverview) {
    return (
      <Card>
        <div className="p-8 text-center">
          <AlertTriangle className="w-10 h-10 text-[#EF4444] mx-auto mb-4" />
          <p className="text-white font-medium mb-2">Failed to load macro data</p>
          <p className="text-sm text-[#8B8B8B] mb-4">{errorOverview}</p>
          <button
            onClick={refreshOverview}
            className="px-4 py-2 rounded-lg text-sm text-[#C9A646] border border-[#C9A646]/30 hover:bg-[#C9A646]/10"
          >
            <RefreshCw className="w-4 h-4 inline mr-2" /> Retry
          </button>
        </div>
      </Card>
    );
  }

  if (loadingOverview || !overview) {
    return (
      <div className="space-y-6">
        <SectionSkeleton height="h-32" />
        <SectionSkeleton height="h-48" />
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <SectionSkeleton height="h-64" />
          <SectionSkeleton height="h-64" />
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header Card */}
      <Card highlight>
        <div className="relative p-6">
          <div className="absolute top-0 left-0 w-1 h-full bg-gradient-to-b from-[#C9A646] via-[#F4D97B] to-transparent" />
          <div className="flex items-center gap-3 mb-2">
            <div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{
              background: 'linear-gradient(135deg, rgba(201,166,70,0.2), rgba(244,217,123,0.1))',
              border: '1px solid rgba(201,166,70,0.3)'
            }}>
              <Brain className="w-5 h-5 text-[#C9A646]" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-white">AI Macro Strategist</h2>
              <p className="text-xs text-[#8B8B8B]">
                GPT-4o analysis of {overview.indicators.length} live indicators from FRED & Yahoo Finance
              </p>
            </div>
          </div>
          <p className="text-[10px] text-[#6B6B6B] flex items-center gap-2 mt-2">
            <Shield className="w-3 h-3 text-[#C9A646]" />
            AI responses cached on server for all users · Data refreshes automatically
          </p>
        </div>
      </Card>

      {/* Live Data Feed */}
      <DataHealthDashboard overview={overview} global={global} fed={fed} />

      {/* Signal Dashboard (no AI, instant) */}
      <QuickSignals overview={overview} fed={fed} />

      {/* Top Movers */}
      <LazySection fallbackHeight="h-48">
        <KeyMovers indicators={overview.indicators} />
      </LazySection>

      {/* AI: Market Regime (auto-generated) */}
      <AISectionCard
        icon={Target}
        title="Market Regime Analysis"
        subtitle="AI assessment of current economic regime & key drivers"
        response={regime.response}
        isLoading={regime.isLoading}
        error={regime.error}
        fromCache={regime.fromCache}
        ageMinutes={regime.ageMinutes}
        rateLimited={regime.rateLimited}
        onGenerate={regime.generate}
        autoGenerated
        accentColor="#C9A646"
      />

      {/* AI: Positioning + Risk (on-demand) */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <LazySection fallbackHeight="h-64">
          <AISectionCard
            icon={PieChart}
            title="Portfolio Positioning"
            subtitle="Sector allocation, factor tilts & trade ideas"
            response={positioning.response}
            isLoading={positioning.isLoading}
            error={positioning.error}
            fromCache={positioning.fromCache}
            ageMinutes={positioning.ageMinutes}
            rateLimited={positioning.rateLimited}
            onGenerate={positioning.generate}
            accentColor="#22C55E"
          />
        </LazySection>
        <LazySection fallbackHeight="h-64">
          <AISectionCard
            icon={Shield}
            title="Risk Radar"
            subtitle="Tail risks, early warnings & hedging playbook"
            response={risk.response}
            isLoading={risk.isLoading}
            error={risk.error}
            fromCache={risk.fromCache}
            ageMinutes={risk.ageMinutes}
            rateLimited={risk.rateLimited}
            onGenerate={risk.generate}
            accentColor="#EF4444"
          />
        </LazySection>
      </div>

      {/* Footer */}
      <div className="flex items-center justify-center gap-2 text-xs text-[#6B6B6B]">
        <Sparkles className="w-3 h-3 text-[#C9A646]" />
        AI analysis by GPT-4o · Data from FRED & Yahoo Finance · Not financial advice
        <button
          onClick={refreshOverview}
          className="text-[#C9A646] hover:text-[#F4D97B] ml-2 flex items-center gap-1"
        >
          <RefreshCw className="w-3 h-3" /> Refresh Data
        </button>
      </div>
    </div>
  );
}

export default memo(AITab);