// src/features/options-ai/components/MethodologyFooter.tsx

import { useState } from 'react';
import { ChevronDown } from 'lucide-react';

const METHODOLOGY_ITEMS = [
  'Flow analytics are derived from options market data. Spot/quote prices are licensed separately and shown to administrators only.',
  'Unusual flow is flagged when contract volume is elevated relative to open interest (volume ≥ ~500 and volume/OI ≥ ~0.5), then scored by premium size, volume/OI ratio, and trade size.',
  'Institutional Options Flow aggregates large options prints by symbol; it reflects options activity, not dark-pool equity prints.',
  'Squeeze signals are a heuristic score from call-wall open interest, distance to the wall, gamma-exposure state, and volume spikes — not a prediction.',
  'Intraday and multi-day flow shapes labeled "Modeled" are reconstructed from end-of-day totals for visualization, not a tick-by-tick replay.',
  'AI Analysis is generated by a language model from the derived analytics above and may be inaccurate. Educational analysis only — not investment advice.',
];

export function MethodologyFooter() {
  const [open, setOpen] = useState(false);

  return (
    <div className="mt-8 border border-border-ds-subtle rounded-[12px] bg-surface-1 overflow-hidden">
      <button
        type="button"
        onClick={() => setOpen((prev) => !prev)}
        className="flex w-full items-center justify-between px-ds-5 py-ds-4 text-left"
        aria-expanded={open}
      >
        <span className="text-xs font-medium uppercase tracking-[0.1em] text-ink-tertiary">
          Methodology &amp; Disclaimers
        </span>
        <ChevronDown
          className={`h-3.5 w-3.5 shrink-0 text-ink-tertiary transition-transform duration-200 ${open ? 'rotate-180' : ''}`}
        />
      </button>

      {open && (
        <div className="border-t border-border-ds-subtle px-ds-5 pb-ds-5 pt-ds-4">
          <ul className="space-y-ds-3">
            {METHODOLOGY_ITEMS.map((item) => (
              <li key={item.slice(0, 40)} className="flex gap-ds-3">
                <span className="mt-[5px] h-1 w-1 shrink-0 rounded-full bg-ink-muted" aria-hidden="true" />
                <p className="text-xs leading-relaxed text-ink-secondary">{item}</p>
              </li>
            ))}
          </ul>
          <p className="mt-ds-4 text-[11px] text-ink-muted">
            Not investment advice. Markets data may be delayed.
          </p>
        </div>
      )}
    </div>
  );
}

export default MethodologyFooter;
