-- ============================================
-- REFERRAL BEATS INTRO
-- ============================================
-- Purpose: member personal referral codes now beat the organic intro
--          offer — 30% off for 3 discounted months (vs. the organic
--          TRADER30 promo's 30% off for 2 discounted months) — and members
--          may optionally choose their own code before it is provisioned.
-- Date: 2026-07-11
--
-- Changes:
--   1) ensure_member_affiliate(uuid) -> ensure_member_affiliate(uuid, text)
--      adds an optional p_requested_code parameter (self-chosen code,
--      validated + uniqueness-checked; ignored once a code already exists).
--   2) validate_referral_code(text) — new RPC, used by the checkout/signup
--      flow to preview a referral code before Whop is involved.
--   3) affiliate_config.member_referral — friend_discount_percent 20 -> 30,
--      + new friend_discount_cycles: 3. enabled (kill-switch) untouched.
--
-- Do NOT apply to any DB. This file is authored for review only.
-- ============================================


-- ============================================
-- 1) ensure_member_affiliate — add optional p_requested_code
-- ============================================
-- Signature changes (uuid) -> (uuid, text DEFAULT NULL), so the old
-- single-arg overload must be dropped explicitly before recreating —
-- Postgres treats a different parameter list as a distinct function and
-- would otherwise leave the old one-arg version dangling.

DROP FUNCTION IF EXISTS public.ensure_member_affiliate(uuid);

CREATE OR REPLACE FUNCTION public.ensure_member_affiliate(
  p_user_id UUID,
  p_requested_code TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_enabled BOOLEAN;
  v_profile RECORD;
  v_is_paying BOOLEAN;
  v_existing RECORD;
  v_display_name TEXT;
  v_base_code TEXT;
  v_suffix TEXT;
  v_code TEXT;
  v_attempt INT := 0;
  v_new_id UUID;
  v_i INT;
  v_alphabet CONSTANT TEXT := 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'; -- base32 (Crockford-ish, no 0/1/8/9)
  v_requested_code TEXT;
  v_reserved_codes CONSTANT TEXT[] := ARRAY[
    'TRADER30', 'INTRO30', 'FINOTAUR50', 'WELCOMEBACK', 'WELCOME',
    'FINOTAUR', 'TRADER', 'INTRO', 'ADMIN', 'TEST'
  ];
  v_code_exists BOOLEAN;
BEGIN
  -- 1) Kill-switch
  SELECT COALESCE((config_value->>'enabled')::boolean, FALSE)
  INTO v_enabled
  FROM affiliate_config
  WHERE config_key = 'member_referral';

  IF v_enabled IS NOT TRUE THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'disabled');
  END IF;

  -- 2) Paying-member check.
  -- "Paying" = an ACTIVE paid product, i.e. any of: journal subscription
  -- (account_type != 'free' AND subscription_status = 'active'), newsletter
  -- (newsletter_status = 'active'), Top Secret (top_secret_status = 'active'),
  -- or the unified Platform plan (platform_plan != 'free' AND
  -- platform_subscription_status = 'active'). Trials are deliberately
  -- excluded — a member should have completed a real payment before they can
  -- hand out a referral coupon for a discount funded by commission on real
  -- revenue.
  SELECT * INTO v_profile FROM profiles WHERE id = p_user_id;

  -- NOTE: use FOUND, not "record IS NULL" — a plpgsql record with any NULL
  -- field is neither IS NULL nor IS NOT NULL, which silently breaks both.
  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_paying');
  END IF;

  v_is_paying := (
    (COALESCE(v_profile.account_type, 'free') <> 'free' AND COALESCE(v_profile.subscription_status, '') = 'active')
    OR COALESCE(v_profile.newsletter_status, '') = 'active'
    OR COALESCE(v_profile.top_secret_status, '') = 'active'
    OR (COALESCE(v_profile.platform_plan, 'free') <> 'free' AND COALESCE(v_profile.platform_subscription_status, '') = 'active')
  );

  IF NOT v_is_paying THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'not_paying');
  END IF;

  -- 3) Idempotent: return the existing row if this user already has one.
  -- p_requested_code is intentionally IGNORED here — a member may only
  -- choose their code once, at provisioning time.
  SELECT * INTO v_existing FROM affiliates WHERE user_id = p_user_id;

  IF FOUND THEN
    RETURN jsonb_build_object(
      'ok', true,
      'existing', true,
      'affiliate_code', v_existing.affiliate_code,
      'coupon_code', v_existing.coupon_code,
      'whop_promo_id', v_existing.whop_promo_id
    );
  END IF;

  -- 4) Self-chosen code path (new). If the caller supplied one, validate
  -- format + reserved list + uniqueness and use it verbatim instead of the
  -- autogenerated base+suffix code below.
  IF p_requested_code IS NOT NULL AND TRIM(p_requested_code) <> '' THEN
    v_requested_code := UPPER(TRIM(p_requested_code));

    IF v_requested_code !~ '^[A-Z0-9]{4,15}$' THEN
      RAISE EXCEPTION 'invalid_code';
    END IF;

    IF v_requested_code = ANY(v_reserved_codes) THEN
      RAISE EXCEPTION 'reserved_code';
    END IF;

    SELECT EXISTS(
      SELECT 1 FROM affiliates
      WHERE UPPER(affiliate_code) = v_requested_code
         OR UPPER(coupon_code) = v_requested_code
      UNION ALL
      SELECT 1 FROM affiliate_applications
      WHERE UPPER(requested_code) = v_requested_code
    ) INTO v_code_exists;

    IF v_code_exists THEN
      RAISE EXCEPTION 'code_taken';
    END IF;

    INSERT INTO affiliates (
      user_id, display_name, email,
      affiliate_code, coupon_code, referral_link,
      status, affiliate_type, commission_enabled
    ) VALUES (
      p_user_id,
      COALESCE(NULLIF(TRIM(v_profile.display_name), ''), v_requested_code),
      v_profile.email,
      v_requested_code, v_requested_code,
      'https://finotaur.com/?ref=' || v_requested_code,
      'active', 'member', TRUE
    )
    RETURNING id INTO v_new_id;

    RETURN jsonb_build_object(
      'ok', true,
      'existing', false,
      'affiliate_code', v_requested_code,
      'coupon_code', v_requested_code,
      'whop_promo_id', NULL
    );
  END IF;

  -- 5) Build the base code from the member's display name, falling back to
  -- the local part of their email. affiliates has no first_name/full_name —
  -- profiles.display_name is the closest analogue (see handle_new_user()).
  v_display_name := COALESCE(NULLIF(TRIM(v_profile.display_name), ''), split_part(v_profile.email, '@', 1));
  v_base_code := UPPER(REGEXP_REPLACE(v_display_name, '[^A-Za-z]', '', 'g'));

  IF v_base_code IS NULL OR v_base_code = '' THEN
    v_base_code := 'MEMBER';
  END IF;

  IF LENGTH(v_base_code) > 8 THEN
    v_base_code := SUBSTRING(v_base_code FROM 1 FOR 8);
  END IF;

  -- 6) Generate a unique code (base + 4-char random base32 suffix), retrying
  -- up to 5 times on a unique_violation (affiliate_code / coupon_code are
  -- both UNIQUE on the affiliates table).
  LOOP
    v_attempt := v_attempt + 1;

    v_suffix := '';
    FOR v_i IN 1..4 LOOP
      v_suffix := v_suffix || SUBSTRING(v_alphabet FROM (GET_BYTE(gen_random_bytes(1), 0) % 32) + 1 FOR 1);
    END LOOP;

    v_code := v_base_code || v_suffix;

    BEGIN
      INSERT INTO affiliates (
        user_id, display_name, email,
        affiliate_code, coupon_code, referral_link,
        status, affiliate_type, commission_enabled
      ) VALUES (
        p_user_id,
        COALESCE(NULLIF(TRIM(v_profile.display_name), ''), v_code),
        v_profile.email,
        v_code, v_code,
        'https://finotaur.com/?ref=' || v_code,
        'active', 'member', TRUE
      )
      RETURNING id INTO v_new_id;

      RETURN jsonb_build_object(
        'ok', true,
        'existing', false,
        'affiliate_code', v_code,
        'coupon_code', v_code,
        'whop_promo_id', NULL
      );
    EXCEPTION WHEN unique_violation THEN
      IF v_attempt >= 5 THEN
        RETURN jsonb_build_object('ok', false, 'reason', 'code_generation_failed');
      END IF;
      -- loop again with a fresh random suffix
    END;
  END LOOP;
END;
$$;

GRANT EXECUTE ON FUNCTION public.ensure_member_affiliate(UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ensure_member_affiliate(UUID, TEXT) TO service_role;


-- ============================================
-- 2) validate_referral_code(text) — public-facing code preview
-- ============================================
-- Used by the checkout/signup flow to preview whether a code the visitor
-- typed in is a real, active member referral code, and whose it is —
-- BEFORE any Whop interaction. Read-only, SECURITY DEFINER because
-- affiliates is not readable by anon/unauthenticated visitors via RLS.

CREATE OR REPLACE FUNCTION public.validate_referral_code(p_code TEXT)
RETURNS TABLE(is_valid BOOLEAN, has_promo BOOLEAN, referrer_name TEXT)
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT
    TRUE AS is_valid,
    (a.whop_promo_id IS NOT NULL) AS has_promo,
    a.display_name AS referrer_name
  FROM affiliates a
  WHERE a.status = 'active'
    AND a.affiliate_type = 'member'
    AND (
      UPPER(a.affiliate_code) = UPPER(TRIM(p_code))
      OR UPPER(a.coupon_code) = UPPER(TRIM(p_code))
    )
  LIMIT 1;
$$;

-- No matching row -> SQL function returns zero rows (not a false row) —
-- callers should treat "no rows" the same as is_valid = false.

GRANT EXECUTE ON FUNCTION public.validate_referral_code(TEXT) TO authenticated;


-- ============================================
-- 3) affiliate_config.member_referral — 30% / 3 months
-- ============================================
-- Jsonb merge (||) so any keys this migration doesn't know about are
-- preserved untouched. The kill-switch (`enabled`) is NOT part of this
-- merge payload, so it is never touched by this statement.

UPDATE affiliate_config
SET config_value = config_value || '{
  "friend_discount_percent": 30,
  "friend_discount_cycles": 3
}'::JSONB,
    updated_at = NOW()
WHERE config_key = 'member_referral';
